pipeline {

    agent any


    environment {

        IMAGE_NAME = "ai-threat-detection"
        IMAGE_TAG  = "latest"
        DOCKER_NETWORK = "devsecops-net"

    }


    stages {


        stage('Checkout Source Code') {

            steps {

                checkout scm

            }

        }



        stage('Setup Python Environment') {

            steps {

                sh '''

                echo "Creating Python virtual environment"


                cd app


                python3 -m venv venv


                . venv/bin/activate


                pip install --upgrade pip


                pip install -r requirements.txt


                '''

            }

        }





        stage('Run Unit Tests') {

            steps {

                sh '''

                echo "Running Flask application tests"


                cd app


                . venv/bin/activate


                pytest tests \
                --junitxml=test-results.xml \
                --verbose


                '''

            }

        }






        stage('SonarQube Analysis') {

            steps {

                withSonarQubeEnv('SonarQube') {

                    sh '''

                    echo "Running SonarQube analysis"


                    sonar-scanner \
                    -Dsonar.projectKey=ai-threat-detection \
                    -Dsonar.projectName=ai-threat-detection \
                    -Dsonar.sources=app \
                    -Dsonar.python.version=3.13


                    '''

                }

            }

        }






        stage('SonarQube Quality Gate') {

            steps {

                timeout(time: 5, unit: 'MINUTES') {


                    echo "Checking SonarQube Quality Gate"


                    waitForQualityGate abortPipeline: true


                }

            }

        }








        stage('Build Docker Image') {

            steps {

                sh '''

                echo "Building Docker image"


                docker build \
                -t ${IMAGE_NAME}:${IMAGE_TAG} \
                app


                '''

            }

        }







        stage('Trivy Security Scan') {

            steps {

                sh '''

                echo "Scanning Docker image using Trivy"


                mkdir -p trivy/reports



                trivy image \
                --severity HIGH,CRITICAL \
                --exit-code 1 \
                --format table \
                --output trivy/reports/trivy-report.txt \
                ${IMAGE_NAME}:${IMAGE_TAG}



                '''

            }

        }








        stage('Create Docker Network') {

            steps {

                sh '''

                echo "Creating Docker network"


                docker network create ${DOCKER_NETWORK} || true


                '''

            }

        }









        stage('Deploy Flask Container') {

            steps {

                sh '''

                echo "Deploying Flask container"



                docker rm -f flask-app || true



                docker run -d \
                --name flask-app \
                --restart unless-stopped \
                --network ${DOCKER_NETWORK} \
                -p 5000:5000 \
                ${IMAGE_NAME}:${IMAGE_TAG}



                '''

            }

        }









        stage('Verify Application') {

            steps {

                sh '''

                echo "Checking Flask application health"



                for i in {1..12}

                do


                    if curl -f http://localhost:5000/health

                    then


                        echo "Application is healthy"


                        exit 0


                    fi



                    echo "Waiting for application startup..."



                    sleep 5



                done




                echo "Application failed to start"



                docker logs flask-app



                exit 1



                '''

            }

        }



    }







    post {


        always {


            echo "Collecting reports"



            junit allowEmptyResults: true,
            testResults: 'app/test-results.xml'





            archiveArtifacts(

                artifacts: 'trivy/reports/*',

                fingerprint: true,

                allowEmptyArchive: true

            )


        }






        success {


            echo "Pipeline completed successfully."


        }






        failure {


            echo "Pipeline failed. Check console logs."


        }


    }


}
